version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fantasy-sports-predictor"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXXXXX"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
s3_prefix = "fantasy-sports-predictor"
disable_rollback = true
resolve_s3 = true

[default.build]
[default.build.parameters]
use_container = true
cached = true
parallel = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER" 